# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f627866fe7fc45cdbdfb2f707a02ca26414f92d38df50e7ab3b87b0fe9858ac9c7b42cabc636a78f991aa7b870d17f183a8608de6ba855ba23c19d6f40ac716

test:
  secret_key_base: 9e275387777cd982678a7f89b59b8dab51a667ed069547456dee2eeb46e4e75982ffe4a1817a6a92c9ad5e146b595514a1423ea35cc4ffe0404c4155221f135d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
